language: node_js

# Run tests on 0.8 to support people using old node versions and 0.10 to
# match what most people are using in the wild.
node_js:
  - "0.8"
  - "0.10"

services:
  - mongodb
  - elasticsearch

before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -y update
  # don't try to install mongo or elasticsearch as they conflict with the services provided by travis
  # don't install compass using apt as the paths then get confused with the rnm. Use gem instead.
  - sudo apt-get -y install `cut -d " " -f 1 config/packages | egrep -v "(^#|mongodb|compass|elasticsearch)"`
  - gem install watir-webdriver -v 0.6.7
  - gem install pry -v 0.9.12.6
  - gem install sass -v 3.2.14
  - gem install compass -v 0.12.2

notifications:
  irc:
    channels:
      - "irc.mysociety.org#popit"
    use_notice: true
